/** 动态设定账本字段中文标签（展示层专用）。 */
export const DYNAMIC_FIELD_LABELS: Record<string, string> = {
  id: 'ID',
  name: '名称',
  status: '状态',
  level: '等级',
  health: '健康',
  // ---- 题材人物状态维度标签 ----
  identity: '身份',
  career: '职业',
  situation: '处境',
  assets: '资产',
  relations: '关系',
  mood: '情绪',
  goal: '目标',
  secret: '秘密',
  realm: '境界',
  combat_power: '战力',
  cultivation: '修为',
  injury: '伤势',
  artifact: '法宝',
  technique: '功法',
  faction: '势力',
  resources: '资源',
  enemy: '仇敌',
  ability: '能力',
  body: '机体健康',
  equipment: '装备',
  clearance: '权限',
  location: '位置',
  stance: '立场',
  office: '职位爵位',
  family: '家世',
  reputation: '声望',
  leverage: '把柄',
  clues: '掌握线索',
  suspicion: '嫌疑',
  motive: '动机',
  whereabouts: '去向',
  alive: '存活',
  job: '职业',
  skills: '技能',
  inventory: '背包',
  hp_mp: '生命法力',
  quest: '任务',
  misunderstanding: '误会隔阂',
  engagement: '婚约',
  survival: '生存状态',
  supplies: '物资',
  team: '队伍',
  base: '据点',
  threat: '威胁',
  form: '状态',
  record: '战绩',
  role: '身份职务',
  opponent: '对手',
  owner: '持有者',
  current_owner: '当前持有者',
  previous_owner: '前任持有者',
  chapter: '章节',
  planted_chapter: '埋设章',
  expected_chapter: '期望回收章',
  description: '描述',
  time: '时间',
  event: '事件',
  fact: '事实',
  summary: '摘要',
  hook: '章尾钩子',
  type: '类型',
  content: '内容',
  word_count: '字数',
  updated_at: '更新时间',
}

export function fieldLabel(key: string): string {
  return DYNAMIC_FIELD_LABELS[key] || key
}

export function stringifyValue(value: unknown): string {
  if (value === null || value === undefined) return ''
  if (typeof value === 'object') return JSON.stringify(value)
  return String(value)
}
